### ISSUE TITLE
-d, --dir gives me "thread 'main' panicked" and other errors

### ISSUE THREAD

**Issue by butuzov** [o2sh/onefetch#134]
Trying to run `onefetch` against an existing directory and having

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:378:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

here is with `RUN_BACKTRACE=1`

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:378:21
stack backtrace:
   0: std::sys_common::backtrace::print
   1: std::panicking::default_hook::{{closure}}
   2: std::panicking::default_hook
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::continue_panic_fmt
   5: rust_begin_unwind
   6: core::panicking::panic_fmt
   7: core::panicking::panic
   8: onefetch::main
   9: std::rt::lang_start::{{closure}}
  10: std::panicking::try::do_call
  11: __rust_maybe_catch_panic
  12: std::rt::lang_start_internal
  13: main
```

------
Trying to run `onefetch` against an **not**existing directory and having

```txt
Error: Could not find any source code in this directory
```
----
Trying to run `onefetch` with -d or --dir empty

```txt
Error: This is not a Git Repo
```

Os: Darwin 
Version: onefetch 1.6.5

**Comment by o2sh** [comment]
This was also fixed in 1.7.0

**Comment by butuzov** [comment]
wow. got it. will wait for the next brew release =)

**Comment by butuzov** [comment]
```
 > onefetch -d ss
Error: This is not a Git Repo
 > onefetch --dir
Error: This is not a Git Repo
 > onefetch --dir wp-plugins-deploy
     ######     ######          ######   Oleg Butuzov ~ git version 2.23.0
     ######     ######          ######   ---------------------------------
     ######     ######          ######   Project: wp-plugins-deploy
###########################     ######   HEAD: 974cde9 (master, origin/develop, origin/master)
###########################     ######   Version: 0.1
###########################     ######   Created: 2 years, 6 months ago
     ######     ######          ######   Language: Shell
     ######     ######          ######   Author: 100% Oleg Butuzov 6
###########################     ######   Last change: 5 days ago
###########################              Repo: https://github.com/butuzov/wp-plugins-deploy
###########################              Commits: 6
     ######     ######          ######   Lines of code: 287
     ######     ######          ######   Size: 0 bytes (6 files)
     ######     ######          ######   License: ??
```

working!
